---
title: "Read rating table"
author: "Dave Holtschlag"
date: "7/18/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
# library(kable)
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
```

## Read Nursing Home Rating tsv file into R environment.


```{r read_ratings}

# Read in Nursery home ratings
rating <- read.csv(file = 'Data/Nursing Home Rating.tsv', sep = '\t', 
                     header = TRUE, stringsAsFactors = FALSE,
                     colClasses = c('character', 'character', 'factor'))

# Read in Nursery home info
# Note: read.csv was more robust reading the table than read.table
provider <- read.csv(file = 'Data/Nursing Home Provider_Info.tsv', sep='\t',
                       header = TRUE, stringsAsFactors = FALSE)

# Add field to get breakdown by: "For profit" "Non profit" "Government"
provider$Ownership.Type.General <- substr(provider$Ownership.Type, 1, 10)

# left join rating and provider
rate_provide <- left_join(rating, provider, by = 'Federal.Provider.Number')

# left join provider and rating
provide_rate <- left_join(provider, rating, by = 'Federal.Provider.Number')

provide_rate$Special.Focus <- 'None'

ndx <- which(substr(provide_rate$Special.Focus.Status, 1, 3) == 'SFF')

provide_rate$Special.Focus[ndx] <- 'SFF or Candidate'


Special.Focus.State.table <- table(provide_rate$Provider.State,
                                   provide_rate$Special.Focus)

Special.Focus.State.df    <- as.data.frame.matrix(Special.Focus.State.table)

Special.Focus.State.df$SFFc_per <- Special.Focus.State.df$`SFF or Candidate` /
  (Special.Focus.State.df$`SFF or Candidate` + Special.Focus.State.df$None) * 100


```

## Plots 

You can also embed plots, for example:

```{r freq_tables_by_state}

# Ctrl-Shif + M -> '%>%'

# 
provider %>% 
  group_by(Provider.State) %>% 
  summarise(no.nursing.homes.in.state = n(), 
            pop.in.state.nursing.homes = sum(Average.Number.of.Residents.Per.Day)) %>% 
  ggplot(aes(x = reorder(Provider.State, -no.nursing.homes.in.state), 
             y = no.nursing.homes.in.state)) +
  geom_bar(stat = 'identity') +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 9)) +
  scale_y_continuous(breaks = c(2, 10, 50, 100, 200, 500, 1000, 1500), 
                     limits = c(0, 1500), trans = 'sqrt',
                     name = 'Number of Nursing Homes Tracked in State' ) +
  scale_x_discrete(name = 'State Postal Abbreviation')
  

# Summary data for population with missing values
summary_data <- provider %>% 
  group_by(Provider.State) %>% 
  summarise(no.nursing.homes.in.state = n(), 
            pop.in.state.nursing.homes = sum(Average.Number.of.Residents.Per.Day, 
                                             na.rm = TRUE),
            no.missing.nursing.homes = sum(is.na(Average.Number.of.Residents.Per.Day)))

kable(summary_data, 
      caption = 'Table 1. Number of Nursing Homes and Population Served by State') %>%
  kable_styling(bootstrap_options = "striped", fixed_thead = TRUE)  %>%
  scroll_box(width = "95%", height = "400px")

summary_data %>% 
  ggplot(aes(x = reorder(Provider.State, -pop.in.state.nursing.homes), 
             y = pop.in.state.nursing.homes)) +
  geom_bar(stat = 'identity') +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 9)) +
  scale_y_continuous(
    # limits = c(1, 120000),
    breaks = c(0, 5000, 15000, 30000, 60000, 90000), 
                     trans = 'sqrt',
                     name = 'Number of Nursing Home Residents Tracked in State' ) +
  scale_x_discrete(name = 'State Postal Abbreviation')


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
